### ISSUE TITLE
Falcor ROUTE 'videosById[{keys:videoIds}].rate': $error is not defined

### ISSUE THREAD

**Issue by HadesArchitect** [KillrVideo/killrvideo-web#25]
![image](https://user-images.githubusercontent.com/1742301/77897938-a64f1a80-727a-11ea-830f-0384b11c2d90.png)

```
web_1        | 2020-03-29T21:40:31.943Z - error: Falcor ROUTE 'videosById[{keys:videoIds}].rate'
web_1        | { callPath:
web_1        |    [ 'videosById',
web_1        |      [ '3abadf87-2c80-43e1-99e6-e71bf0d18a3c' ],
web_1        |      'rate',
web_1        |      videoIds: [ '3abadf87-2c80-43e1-99e6-e71bf0d18a3c' ] ],
web_1        |   callArgs: [ 3 ] }
web_1        |  ReferenceError: $error is not defined
web_1        |     at KillrVideoRouter.call (/opt/killrvideo-web/dist/server/routes/ratings-routes.js:70:16)
web_1        |     at KillrVideoRouter.logCallRequest (/opt/killrvideo-web/dist/server/routes/decorators/log-requests.js:90:32)
web_1        |     at KillrVideoRouter.innerCreateNamedVariables (/opt/killrvideo-web/node_modules/falcor-router/src/parse-tree/actionWrapper.js:41:23)
web_1        |     at /opt/killrvideo-web/node_modules/falcor-router/src/run/call/runCallAction.js:35:32
web_1        |     at tryCatcher (/opt/killrvideo-web/node_modules/falcor-router/node_modules/rx/dist/rx.js:63:31)
web_1        |     at Defer.subscribeCore (/opt/killrvideo-web/node_modules/falcor-router/node_modules/rx/dist/rx.js:2536:37)
web_1        |     at Defer.tryCatcher (/opt/killrvideo-web/node_modules/falcor-router/node_modules/rx/dist/rx.js:63:31)
web_1        |     at setDisposable (/opt/killrvideo-web/node_modules/falcor-router/node_modules/rx/dist/rx.js:2082:46)
web_1        |     at Defer.Rx.ObservableBase.ObservableBase._subscribe (/opt/killrvideo-web/node_modules/falcor-router/node_modules/rx/dist/rx.js:2097:9)
web_1        |     at Defer.Rx.Observable.observableProto.subscribe.observableProto.forEach (/opt/killrvideo-web/node_modules/falcor-router/node_modules/rx/dist/rx.js:2034:19)
web_1        |     at MapObservable.subscribeCore (/opt/killrvideo-web/node_modules/falcor-router/node_modules/rx/dist/rx.js:5394:26)
web_1        |     at MapObservable.tryCatcher (/opt/killrvideo-web/node_modules/falcor-router/node_modules/rx/dist/rx.js:63:31)
web_1        |     at setDisposable (/opt/killrvideo-web/node_modules/falcor-router/node_modules/rx/dist/rx.js:2082:46)
web_1        |     at MapObservable.Rx.ObservableBase.ObservableBase._subscribe (/opt/killrvideo-web/node_modules/falcor-router/node_modules/rx/dist/rx.js:2097:9)
web_1        |     at MapObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/opt/killrvideo-web/node_modules/falcor-router/node_modules/rx/dist/rx.js:2034:19)
web_1        |     at TapObservable.subscribeCore (/opt/killrvideo-web/node_modules/falcor-router/node_modules/rx/dist/rx.js:4510:26)
web_1        | 2020-03-29T21:40:32.605Z - error: Falcor ROUTE 'videosById[{keys:videoIds}].rate'
```

**Comment by HadesArchitect** [comment]
Found this in logs on production, not sure what's going on here. Hope to take a look later.
